main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('animals/', views.animals_index, name='index'),
    path('animals/<int:animal_id>/', views.animals_detail, name='detail'),
    path('animals/create/', views.AnimalCreate.as_view(), name='animals_create'),
    path('animals/<int:pk>/update/', views.AnimalUpdate.as_view(), name='animals_update'),
    path('animals/<int:pk>/delete/', views.AnimalDelete.as_view(), name='animals_delete'),
    path('animals/<int:animal_id>/add_visit/', views.add_visit, name='add_visit'),
    path('animals/<int:animal_id>/assoc_immunization/<int:immunization_id>/', views.assoc_immunization, name='assoc_immunization'),
    path('animals/<int:animal_id>/add_photo/', views.add_photo, name='add_photo'),
    path('immunization/', views.ImmunizationList.as_view(), name='immunizations_index'),
    path('immunization/<int:pk>/', views.ImmunizationDetail.as_view(), name='immunizations_detail'),
    path('immunization/create/', views.ImmunizationCreate.as_view(), name='immunizations_create'),
    path('immunization/<int:pk>/update/', views.ImmunizationUpdate.as_view(), name='immunizations_update'),
    path('immunization/<int:pk>/delete/', views.ImmunizationDelete.as_view(), name='immunizations_delete'),
]

rescueanimals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

SPECIES = (
    ('C', 'Cat'),
    ('D', 'Dog'),
    ('O', 'Other'),
    ('R', 'Rabbit')
)

# Create your models here.
class Immunization(models.Model):
    name = models.CharField(max_length=150)
    type = models.CharField(
        max_length=1,
        choices=SPECIES,
        default=SPECIES[1][0]
    )

class Animal(models.Model):
    name = models.CharField(max_length=25)
    type = models.CharField(
        max_length=1,
        choices=SPECIES,
        default=SPECIES[1][0]
    )
    breed = models.CharField(max_length=50)
    description = models.TextField()
    age = models.IntegerField()
    immunizations = models.ManyToManyField(Immunization)

    def __str__(self):
        return f'{self.name} is {self.age} years old'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'animal_id': self.id})

    class Meta:
        ordering = ['type']

class Visit(models.Model):
    name = models.CharField(max_length=100)        
    phoneNumber = models.CharField(max_length=15)
    date = models.DateField('Meet & Greet Date')
    time = models.CharField(max_length=10)

    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} is coming for a meet and greet on {self.date} at {self.time}'

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for animal_id: {self.animal_id} @ {self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Visit

class VisitForm(ModelForm):
    class Meta:
        model = Visit
        fields = ['name', 'phoneNumber', 'date', 'time']
        

main_app/views.py
from botocore.retries import bucket
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
import uuid
import boto3
import os
from .models import Animal, Immunization, Photo
from .forms import VisitForm

from main_app import models

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')    

def animals_index(request):
    animals = Animal.objects.all()
    return render(request, 'animals/index.html', { 'animals': animals })

def animals_detail(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    immunizations_animal_doesnt_have = Immunization.objects.exclude(id__in=animal.immunizations.filter(type = animal.type).values_list('id'))
    visit_form = VisitForm()
    return render(request, 'animals/detail.html', { 
        'animal': animal,
        'visit_form': visit_form,
        'immunizations': immunizations_animal_doesnt_have
    })

class AnimalCreate(CreateView):
    model = Animal
    fields = ['name', 'type', 'breed', 'description', 'age'] 

class AnimalUpdate(UpdateView):
    model = Animal
    fields = ['type', 'breed', 'description', 'age']

class AnimalDelete(DeleteView):
    model = Animal
    success_url = '/animals/'

def add_visit(request, animal_id):
    form = VisitForm(request.POST)
    if form.is_valid():
        new_visit = form.save(commit=False)
        new_visit.animal_id = animal_id
        new_visit.save()
    return redirect('detail', animal_id=animal_id)

def add_photo(request, animal_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, animal_id=animal_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', animal_id=animal_id)

class ImmunizationList(ListView):
    model = Immunization

class ImmunizationDetail(DetailView):
    model = Immunization

class ImmunizationCreate(CreateView):
    model = Immunization
    fields = '__all__'
    success_url = '/immunization/create/'

class ImmunizationUpdate(UpdateView):
    model = Immunization
    fields = '__all__'

class ImmunizationDelete(DeleteView):
    model = Immunization
    success_url = '/immunizations/'

def assoc_immunization(request, animal_id, immunization_id):
    Animal.objects.get(id=animal_id).immunizations.add(immunization_id)
    return redirect('detail', animal_id=animal_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About Rescue Animals</h1>
    <hr/>
    <p>Come adopt an animal.</p>
    <p>They are in need of a loving home!</p>
{% endblock %}

main_app/templates/animals/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Animal Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ animal.name }}</span>
        <p>Type: {{ animal.get_species_display }}</p>
        <p>Breed: {{ animal.breed }}</p>
        <p>Description: {{ animal.description }}</p>
        <p>Age: {{ animal.age }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'animals_update' animal.id %}">Edit</a>
        <a href="{% url 'animals_delete' animal.id %}">Delete</a>
      </div>
    </div>
    {% for photo in animal.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' animal.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_visit' animal.id %}" method="POST">
      {% csrf_token %}
      {{ visit_form.as_p }}
      <input type="submit" class="btn" value="Add Visit">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Name</th><th>Phone Number</th><th>Date</th><th>Time</th></tr>
      </thead>
      <tbody>
        {% for visit in animal.visit_set.all %}
          <tr>
            <td>{{visit.name}}</td>
            <td>{{visit.phoneNumber}}</td>
            <td>{{visit.date}}</td>
            <td>{{visit.time}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div>
  <h4>{{ animal.name }}'s Immunizations</h4>
    {% if animal.immunizations.count %}
    <div>
      {% for immunization in animal.immunizations.all %}
        <div><span class="badge left blue-text">{{ immunization.name }}</span></div>
      {% endfor %}
    </div>
    {% else %}
    <h5>No Immunizations 💉🩺</h5>
    {% endif %}
    <hr>
  <div class="col s6">
    <h3>Available Immunizations</h3>
    {% if immunizations %}
      {% for immunization in immunizations %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               {{ immunization.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_immunization' animal.id immunization.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
      <hr>
    {% else %}
      <h5>{{animal.name}} Already Has All Immunizations Available</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_species');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/animals/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Animal List</h1>

{% for animal in animals %}
    <div class="card">
        <a href="{% url 'detail' animal.id %}">
            <div class="card-content">
                <span class="card-title">{{ animal.name }}</span>
                <p>Type: {{ animal.get_type_display }}</p>
                <p>Breed: {{ animal.breed }}</p>
                <p>Description: {{ animal.description }}</p>
                <p>Age: {{ animal.age }}</p>
            </div>
        </a>    
    </div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Animal Rescue</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper #ffa000 amber darken-2">
                <ul>
                    <li><a href="{% url 'home' %}">AnimalRescue</a></li>
                </ul>
                <ul>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'immunizations_create' %}">Add Immunization</a></li>
                    <li><a href="{% url 'animals_create' %}">Add a Animal</a></li>
                    <li><a href="{% url 'index' %}">View All Rescue Animals</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="center #ffa000 amber darken-2">All Rights Reserved, &copy; 2021 Rescue Animals &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to Animal Rescue</h1>

{% endblock %}

main_app/templates/main_app/animal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Animal</h1>

  <h4>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn">
    <a href="{% url 'detail' animal.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/animal_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Animal</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/immunization_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="blue-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Immunization</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>

  <script>  
    const selectEl = document.getElementById('id_type');
    M.FormSelect.init(selectEl);
  </script>

{% endblock %}